inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# RSpec関連の設定
RSpec/DescribedClass:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# 日本語の文字列を許可
Style/AsciiComments:
  Enabled: false

# ブロックの行数制限を緩和
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# RSpecのブロック内での長いブロックを許可
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
