default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>

development:
  <<: *default
  database: nishikocloud_dev

test:
  <<: *default
  database: nishikocloud_test

production:
  <<: *default
  database: nishikocloud_prod

