development:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: nishikocloud_dev
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  database: nishikocloud_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: nishikocloud_prod
  host: localhost
  username: root
  password: 

